// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJABEpaKXCiUQA31ObEfwcvY3f-YA31PM',
    appId: '1:397314364189:web:94969a2d4c2b25e42147f4',
    messagingSenderId: '397314364189',
    projectId: 'flutter-application-1-c25a5',
    authDomain: 'flutter-application-1-c25a5.firebaseapp.com',
    storageBucket: 'flutter-application-1-c25a5.firebasestorage.app',
    measurementId: 'G-SLRKETJFE4',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbmwKEFIJBplNHUW7dZ3ZQ165ROuFnaYo',
    appId: '1:397314364189:android:8a38750274465bc82147f4',
    messagingSenderId: '397314364189',
    projectId: 'flutter-application-1-c25a5',
    storageBucket: 'flutter-application-1-c25a5.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbaDGXfxyLNCVzyF9FIgTfYzDB8JAH5S8',
    appId: '1:397314364189:ios:27e6d639865d510f2147f4',
    messagingSenderId: '397314364189',
    projectId: 'flutter-application-1-c25a5',
    storageBucket: 'flutter-application-1-c25a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbaDGXfxyLNCVzyF9FIgTfYzDB8JAH5S8',
    appId: '1:397314364189:ios:27e6d639865d510f2147f4',
    messagingSenderId: '397314364189',
    projectId: 'flutter-application-1-c25a5',
    storageBucket: 'flutter-application-1-c25a5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJABEpaKXCiUQA31ObEfwcvY3f-YA31PM',
    appId: '1:397314364189:web:5c437719946fcb942147f4',
    messagingSenderId: '397314364189',
    projectId: 'flutter-application-1-c25a5',
    authDomain: 'flutter-application-1-c25a5.firebaseapp.com',
    storageBucket: 'flutter-application-1-c25a5.firebasestorage.app',
    measurementId: 'G-VBE6W2P7KS',
  );
}
